#if !canImport(ObjectiveC)
import XCTest

extension OpenSubtitlesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OpenSubtitlesTests = [
        ("testHash", testHash),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OpenSubtitlesTests.__allTests__OpenSubtitlesTests),
    ]
}
#endif
